# Generated by Django 4.0.6 on 2022-08-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Daniel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill_linnk',
            new_name='skill_link',
        ),
    ]
