# Generated by Django 4.0.6 on 2022-08-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daniel', '0002_rename_skill_linnk_skills_skill_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=30),
        ),
    ]
