# Generated by Django 4.0.6 on 2022-08-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daniel', '0003_alter_skills_skill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
